rgname                 = "stage-nikhil-rg"
service_principal_name = "stage-nikhil-spn"
keyvault_name          = "stage-nikhil-kv-101"
SUB_ID = ""
node_pool_name = "stagenp"
cluster_name = "stage-nikhil-cluster"
