rgname                 = "dev-nikhil-rg"
service_principal_name = "dev-nikhil-spn"
keyvault_name          = "dev-nikhil-kv-101"
SUB_ID = ""
cluster_name = "dev-nikhil-cluster"
node_pool_name = "devnp"
